function dR_dxi = dR_dxi(in1,in2)
%DR_DXI
%    DR_DXI = DR_DXI(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Sep-2018 16:31:51

u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
xi1 = in1(1,:);
xi2 = in1(2,:);
xi3 = in1(3,:);
dR_dxi = reshape([0.0,-u3.*exp(-xi1),u2.*exp(xi1),u3.*exp(xi2),0.0,-u1.*exp(-xi2),-u2.*exp(-xi3),u1.*exp(xi3),0.0],[3,3]);
