function invA = Omega2eulerratesMat_ZXY(in1)
%OMEGA2EULERRATESMAT_ZXY
%    INVA = OMEGA2EULERRATESMAT_ZXY(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Sep-2018 17:22:21

p = in1(2,:);
r = in1(1,:);
t2 = sin(p);
t3 = cos(p);
t4 = cos(r);
t5 = 1.0./t4;
t6 = sin(r);
invA = reshape([t3,t2.*t5.*t6,-t2.*t5,0.0,1.0,0.0,t2,-t3.*t5.*t6,t3.*t5],[3,3]);
